In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df_app=pd.read_csv(r"C:\Users\HP\pipeline python\python\python project\Bank loan case study\application_data.csv")
df_app

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49994,157871,0,Cash loans,F,N,N,0,180000.0,1206000.0,45936.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
49995,157872,0,Cash loans,M,N,N,0,126000.0,1125000.0,47794.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
49996,157873,0,Cash loans,M,N,N,1,112500.0,900000.0,26316.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
49997,157874,0,Cash loans,F,N,Y,0,270000.0,820638.0,34897.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,4.0
49998,157875,0,Cash loans,F,N,Y,0,117000.0,254700.0,14751.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
# explore the file
df_app.index

RangeIndex(start=0, stop=49999, step=1)

In [4]:
df_app.shape

(49999, 122)

In [5]:
df_app.size

6099878

In [6]:
# dataframeobject.head([number]) by default -- 5
df_app.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
df_app.tail()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
49994,157871,0,Cash loans,F,N,N,0,180000.0,1206000.0,45936.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
49995,157872,0,Cash loans,M,N,N,0,126000.0,1125000.0,47794.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
49996,157873,0,Cash loans,M,N,N,1,112500.0,900000.0,26316.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
49997,157874,0,Cash loans,F,N,Y,0,270000.0,820638.0,34897.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,4.0
49998,157875,0,Cash loans,F,N,Y,0,117000.0,254700.0,14751.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
df_app.sample(n=10)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
13787,116067,0,Cash loans,F,N,N,0,207000.0,1247121.0,36594.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
6815,107947,0,Revolving loans,F,N,N,0,67500.0,180000.0,9000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
28391,132998,0,Cash loans,M,Y,Y,0,180000.0,755190.0,36328.5,...,0,0,0,0,1.0,0.0,0.0,0.0,0.0,4.0
48760,156468,0,Cash loans,F,N,N,0,90000.0,540000.0,26109.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
25050,129137,0,Cash loans,F,N,Y,0,157500.0,780363.0,31077.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
18016,121009,0,Cash loans,F,N,Y,0,225000.0,1237500.0,36180.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
16611,119378,0,Cash loans,M,N,Y,0,171000.0,508495.5,23692.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
27480,131944,0,Cash loans,F,N,N,0,126000.0,284400.0,16011.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
25758,129946,0,Cash loans,F,N,Y,0,76500.0,119925.0,12415.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
39405,145631,0,Cash loans,F,N,Y,0,180000.0,1051245.0,30865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
df_app.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49999 entries, 0 to 49998
Columns: 122 entries, SK_ID_CURR to AMT_REQ_CREDIT_BUREAU_YEAR
dtypes: float64(64), int64(42), object(16)
memory usage: 46.5+ MB

In [10]:
df_app.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49999 entries, 0 to 49998
Data columns (total 122 columns):
 #    Column                        Dtype
---   ------                        -----
 0    SK_ID_CURR                    int64
 1    TARGET                        int64
 2    NAME_CONTRACT_TYPE            object
 3    CODE_GENDER                   object
 4    FLAG_OWN_CAR                  object
 5    FLAG_OWN_REALTY               object
 6    CNT_CHILDREN                  int64
 7    AMT_INCOME_TOTAL              float64
 8    AMT_CREDIT                    float64
 9    AMT_ANNUITY                   float64
 10   AMT_GOODS_PRICE               float64
 11   NAME_TYPE_SUITE               object
 12   NAME_INCOME_TYPE              object
 13   NAME_EDUCATION_TYPE           object
 14   NAME_FAMILY_STATUS            object
 15   NAME_HOUSING_TYPE             object
 16   REGION_POPULATION_RELATIVE    float64
 17   DAYS_BIRTH                    int64
 18   DAYS_EMPLOYED                 int64
 19   DAYS_REGISTRATION             int64
 20   DAYS_ID_PUBLISH               int64
 21   OWN_CAR_AGE                   float64
 22   FLAG_MOBIL                    int64
 23   FLAG_EMP_PHONE                int64
 24   FLAG_WORK_PHONE               int64
 25   FLAG_CONT_MOBILE              int64
 26   FLAG_PHONE                    int64
 27   FLAG_EMAIL                    int64
 28   OCCUPATION_TYPE               object
 29   CNT_FAM_MEMBERS               float64
 30   REGION_RATING_CLIENT          int64
 31   REGION_RATING_CLIENT_W_CITY   int64
 32   WEEKDAY_APPR_PROCESS_START    object
 33   HOUR_APPR_PROCESS_START       int64
 34   REG_REGION_NOT_LIVE_REGION    int64
 35   REG_REGION_NOT_WORK_REGION    int64
 36   LIVE_REGION_NOT_WORK_REGION   int64
 37   REG_CITY_NOT_LIVE_CITY        int64
 38   REG_CITY_NOT_WORK_CITY        int64
 39   LIVE_CITY_NOT_WORK_CITY       int64
 40   ORGANIZATION_TYPE             object
 41   EXT_SOURCE_1                  float64
 42   EXT_SOURCE_2                  float64
 43   EXT_SOURCE_3                  float64
 44   APARTMENTS_AVG                float64
 45   BASEMENTAREA_AVG              float64
 46   YEARS_BEGINEXPLUATATION_AVG   float64
 47   YEARS_BUILD_AVG               float64
 48   COMMONAREA_AVG                float64
 49   ELEVATORS_AVG                 float64
 50   ENTRANCES_AVG                 float64
 51   FLOORSMAX_AVG                 float64
 52   FLOORSMIN_AVG                 float64
 53   LANDAREA_AVG                  float64
 54   LIVINGAPARTMENTS_AVG          float64
 55   LIVINGAREA_AVG                float64
 56   NONLIVINGAPARTMENTS_AVG       float64
 57   NONLIVINGAREA_AVG             float64
 58   APARTMENTS_MODE               float64
 59   BASEMENTAREA_MODE             float64
 60   YEARS_BEGINEXPLUATATION_MODE  float64
 61   YEARS_BUILD_MODE              float64
 62   COMMONAREA_MODE               float64
 63   ELEVATORS_MODE                float64
 64   ENTRANCES_MODE                float64
 65   FLOORSMAX_MODE                float64
 66   FLOORSMIN_MODE                float64
 67   LANDAREA_MODE                 float64
 68   LIVINGAPARTMENTS_MODE         float64
 69   LIVINGAREA_MODE               float64
 70   NONLIVINGAPARTMENTS_MODE      float64
 71   NONLIVINGAREA_MODE            float64
 72   APARTMENTS_MEDI               float64
 73   BASEMENTAREA_MEDI             float64
 74   YEARS_BEGINEXPLUATATION_MEDI  float64
 75   YEARS_BUILD_MEDI              float64
 76   COMMONAREA_MEDI               float64
 77   ELEVATORS_MEDI                float64
 78   ENTRANCES_MEDI                float64
 79   FLOORSMAX_MEDI                float64
 80   FLOORSMIN_MEDI                float64
 81   LANDAREA_MEDI                 float64
 82   LIVINGAPARTMENTS_MEDI         float64
 83   LIVINGAREA_MEDI               float64
 84   NONLIVINGAPARTMENTS_MEDI      float64
 85   NONLIVINGAREA_MEDI            float64
 86   FONDKAPREMONT_MODE            object
 87   HOUSETYPE_MODE                object
 88   TOTALAREA_MODE                float64
 89   WALLSMATERIAL_MODE            object
 90   EMERGENCYSTATE_MODE           object
 91   OBS_30_CNT_SOCIAL_CIRCLE      float64
 92   DEF_30_CNT_SOCIAL_CIRCLE      float64
 93   OBS_60_CNT_SOCIAL_CIRCLE      float64
 94   DEF_60_CNT_SOCIAL_CIRCLE      float64
 95   DAYS_LAST_PHONE_CHANGE        float64
 96   FLAG_DOCUMENT_2               int64
 97   FLAG_DOCUMENT_3               int64
 98   FLAG_DOCUMENT_4               int64
 99   FLAG_DOCUMENT_5               int64
 100  FLAG_DOCUMENT_6               int64
 101  FLAG_DOCUMENT_7               int64
 102  FLAG_DOCUMENT_8               int64
 103  FLAG_DOCUMENT_9               int64
 104  FLAG_DOCUMENT_10              int64
 105  FLAG_DOCUMENT_11              int64
 106  FLAG_DOCUMENT_12              int64
 107  FLAG_DOCUMENT_13              int64
 108  FLAG_DOCUMENT_14              int64
 109  FLAG_DOCUMENT_15              int64
 110  FLAG_DOCUMENT_16              int64
 111  FLAG_DOCUMENT_17              int64
 112  FLAG_DOCUMENT_18              int64
 113  FLAG_DOCUMENT_19              int64
 114  FLAG_DOCUMENT_20              int64
 115  FLAG_DOCUMENT_21              int64
 116  AMT_REQ_CREDIT_BUREAU_HOUR    float64
 117  AMT_REQ_CREDIT_BUREAU_DAY     float64
 118  AMT_REQ_CREDIT_BUREAU_WEEK    float64
 119  AMT_REQ_CREDIT_BUREAU_MON     float64
 120  AMT_REQ_CREDIT_BUREAU_QRT     float64
 121  AMT_REQ_CREDIT_BUREAU_YEAR    float64
dtypes: float64(64), int64(42), object(16)
memory usage: 46.5+ MB

In [11]:
df_app.info(verbose=True,show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49999 entries, 0 to 49998
Data columns (total 122 columns):
 #    Column                        Non-Null Count  Dtype
---   ------                        --------------  -----
 0    SK_ID_CURR                    49999 non-null  int64
 1    TARGET                        49999 non-null  int64
 2    NAME_CONTRACT_TYPE            49999 non-null  object
 3    CODE_GENDER                   49999 non-null  object
 4    FLAG_OWN_CAR                  49999 non-null  object
 5    FLAG_OWN_REALTY               49999 non-null  object
 6    CNT_CHILDREN                  49999 non-null  int64
 7    AMT_INCOME_TOTAL              49999 non-null  float64
 8    AMT_CREDIT                    49999 non-null  float64
 9    AMT_ANNUITY                   49998 non-null  float64
 10   AMT_GOODS_PRICE               49961 non-null  float64
 11   NAME_TYPE_SUITE               49807 non-null  object
 12   NAME_INCOME_TYPE              49999 non-null  object
 13   NAME_EDUCATION_TYPE           49999 non-null  object
 14   NAME_FAMILY_STATUS            49999 non-null  object
 15   NAME_HOUSING_TYPE             49999 non-null  object
 16   REGION_POPULATION_RELATIVE    49999 non-null  float64
 17   DAYS_BIRTH                    49999 non-null  int64
 18   DAYS_EMPLOYED                 49999 non-null  int64
 19   DAYS_REGISTRATION             49999 non-null  int64
 20   DAYS_ID_PUBLISH               49999 non-null  int64
 21   OWN_CAR_AGE                   17049 non-null  float64
 22   FLAG_MOBIL                    49999 non-null  int64
 23   FLAG_EMP_PHONE                49999 non-null  int64
 24   FLAG_WORK_PHONE               49999 non-null  int64
 25   FLAG_CONT_MOBILE              49999 non-null  int64
 26   FLAG_PHONE                    49999 non-null  int64
 27   FLAG_EMAIL                    49999 non-null  int64
 28   OCCUPATION_TYPE               34345 non-null  object
 29   CNT_FAM_MEMBERS               49998 non-null  float64
 30   REGION_RATING_CLIENT          49999 non-null  int64
 31   REGION_RATING_CLIENT_W_CITY   49999 non-null  int64
 32   WEEKDAY_APPR_PROCESS_START    49999 non-null  object
 33   HOUR_APPR_PROCESS_START       49999 non-null  int64
 34   REG_REGION_NOT_LIVE_REGION    49999 non-null  int64
 35   REG_REGION_NOT_WORK_REGION    49999 non-null  int64
 36   LIVE_REGION_NOT_WORK_REGION   49999 non-null  int64
 37   REG_CITY_NOT_LIVE_CITY        49999 non-null  int64
 38   REG_CITY_NOT_WORK_CITY        49999 non-null  int64
 39   LIVE_CITY_NOT_WORK_CITY       49999 non-null  int64
 40   ORGANIZATION_TYPE             49999 non-null  object
 41   EXT_SOURCE_1                  21827 non-null  float64
 42   EXT_SOURCE_2                  49873 non-null  float64
 43   EXT_SOURCE_3                  40055 non-null  float64
 44   APARTMENTS_AVG                24614 non-null  float64
 45   BASEMENTAREA_AVG              20800 non-null  float64
 46   YEARS_BEGINEXPLUATATION_AVG   25605 non-null  float64
 47   YEARS_BUILD_AVG               16760 non-null  float64
 48   COMMONAREA_AVG                15039 non-null  float64
 49   ELEVATORS_AVG                 23348 non-null  float64
 50   ENTRANCES_AVG                 24804 non-null  float64
 51   FLOORSMAX_AVG                 25124 non-null  float64
 52   FLOORSMIN_AVG                 16105 non-null  float64
 53   LANDAREA_AVG                  20278 non-null  float64
 54   LIVINGAPARTMENTS_AVG          15773 non-null  float64
 55   LIVINGAREA_AVG                24862 non-null  float64
 56   NONLIVINGAPARTMENTS_AVG       15285 non-null  float64
 57   NONLIVINGAREA_AVG             22427 non-null  float64
 58   APARTMENTS_MODE               24614 non-null  float64
 59   BASEMENTAREA_MODE             20800 non-null  float64
 60   YEARS_BEGINEXPLUATATION_MODE  25605 non-null  float64
 61   YEARS_BUILD_MODE              16760 non-null  float64
 62   COMMONAREA_MODE               15039 non-null  float64
 63   ELEVATORS_MODE                23348 non-null  float64
 64   ENTRANCES_MODE                24804 non-null  float64
 65   FLOORSMAX_MODE                25124 non-null  float64
 66   FLOORSMIN_MODE                16105 non-null  float64
 67   LANDAREA_MODE                 20278 non-null  float64
 68   LIVINGAPARTMENTS_MODE         15773 non-null  float64
 69   LIVINGAREA_MODE               24862 non-null  float64
 70   NONLIVINGAPARTMENTS_MODE      15285 non-null  float64
 71   NONLIVINGAREA_MODE            22427 non-null  float64
 72   APARTMENTS_MEDI               24614 non-null  float64
 73   BASEMENTAREA_MEDI             20800 non-null  float64
 74   YEARS_BEGINEXPLUATATION_MEDI  25605 non-null  float64
 75   YEARS_BUILD_MEDI              16760 non-null  float64
 76   COMMONAREA_MEDI               15039 non-null  float64
 77   ELEVATORS_MEDI                23348 non-null  float64
 78   ENTRANCES_MEDI                24804 non-null  float64
 79   FLOORSMAX_MEDI                25124 non-null  float64
 80   FLOORSMIN_MEDI                16105 non-null  float64
 81   LANDAREA_MEDI                 20278 non-null  float64
 82   LIVINGAPARTMENTS_MEDI         15773 non-null  float64
 83   LIVINGAREA_MEDI               24862 non-null  float64
 84   NONLIVINGAPARTMENTS_MEDI      15285 non-null  float64
 85   NONLIVINGAREA_MEDI            22427 non-null  float64
 86   FONDKAPREMONT_MODE            15808 non-null  object
 87   HOUSETYPE_MODE                24924 non-null  object
 88   TOTALAREA_MODE                25851 non-null  float64
 89   WALLSMATERIAL_MODE            24540 non-null  object
 90   EMERGENCYSTATE_MODE           26301 non-null  object
 91   OBS_30_CNT_SOCIAL_CIRCLE      49831 non-null  float64
 92   DEF_30_CNT_SOCIAL_CIRCLE      49831 non-null  float64
 93   OBS_60_CNT_SOCIAL_CIRCLE      49831 non-null  float64
 94   DEF_60_CNT_SOCIAL_CIRCLE      49831 non-null  float64
 95   DAYS_LAST_PHONE_CHANGE        49998 non-null  float64
 96   FLAG_DOCUMENT_2               49999 non-null  int64
 97   FLAG_DOCUMENT_3               49999 non-null  int64
 98   FLAG_DOCUMENT_4               49999 non-null  int64
 99   FLAG_DOCUMENT_5               49999 non-null  int64
 100  FLAG_DOCUMENT_6               49999 non-null  int64
 101  FLAG_DOCUMENT_7               49999 non-null  int64
 102  FLAG_DOCUMENT_8               49999 non-null  int64
 103  FLAG_DOCUMENT_9               49999 non-null  int64
 104  FLAG_DOCUMENT_10              49999 non-null  int64
 105  FLAG_DOCUMENT_11              49999 non-null  int64
 106  FLAG_DOCUMENT_12              49999 non-null  int64
 107  FLAG_DOCUMENT_13              49999 non-null  int64
 108  FLAG_DOCUMENT_14              49999 non-null  int64
 109  FLAG_DOCUMENT_15              49999 non-null  int64
 110  FLAG_DOCUMENT_16              49999 non-null  int64
 111  FLAG_DOCUMENT_17              49999 non-null  int64
 112  FLAG_DOCUMENT_18              49999 non-null  int64
 113  FLAG_DOCUMENT_19              49999 non-null  int64
 114  FLAG_DOCUMENT_20              49999 non-null  int64
 115  FLAG_DOCUMENT_21              49999 non-null  int64
 116  AMT_REQ_CREDIT_BUREAU_HOUR    43265 non-null  float64
 117  AMT_REQ_CREDIT_BUREAU_DAY     43265 non-null  float64
 118  AMT_REQ_CREDIT_BUREAU_WEEK    43265 non-null  float64
 119  AMT_REQ_CREDIT_BUREAU_MON     43265 non-null  float64
 120  AMT_REQ_CREDIT_BUREAU_QRT     43265 non-null  float64
 121  AMT_REQ_CREDIT_BUREAU_YEAR    43265 non-null  float64
dtypes: float64(64), int64(42), object(16)
memory usage: 46.5+ MB

In [12]:
df_app.columns

Index(['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER',
       'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY',
       ...
       'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20',
       'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR',
       'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
       'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT',
       'AMT_REQ_CREDIT_BUREAU_YEAR'],
      dtype='object', length=122)

In [13]:
df_app.dtypes

SK_ID_CURR                      int64
TARGET                          int64
NAME_CONTRACT_TYPE             object
CODE_GENDER                    object
FLAG_OWN_CAR                   object
                               ...
AMT_REQ_CREDIT_BUREAU_DAY     float64
AMT_REQ_CREDIT_BUREAU_WEEK    float64
AMT_REQ_CREDIT_BUREAU_MON     float64
AMT_REQ_CREDIT_BUREAU_QRT     float64
AMT_REQ_CREDIT_BUREAU_YEAR    float64
Length: 122, dtype: object

In [14]:
df_app.describe()

,SK_ID_CURR,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
count,49999.000000,49999.000000,49999.000000,4.999900e+04,4.999900e+04,49998.000000,4.996100e+04,49999.000000,49999.000000,49999.000000,...,49999.000000,49999.000000,49999.000000,49999.00000,43265.000000,43265.000000,43265.000000,43265.000000,43265.000000,43265.000000
mean,129013.210584,0.080522,0.419848,1.707676e+05,5.997006e+05,27107.377355,5.390600e+05,0.020798,-16022.042081,63219.424488,...,0.008500,0.000700,0.000520,0.00038,0.007096,0.007512,0.032382,0.270288,0.260973,1.881035
std,16690.512048,0.272102,0.724039,5.318191e+05,4.024154e+05,14562.944435,3.698533e+05,0.013761,4361.400270,140794.605668,...,0.091805,0.026449,0.022798,0.01949,0.087709,0.107992,0.194080,0.928560,0.606996,1.865054
min,100002.000000,0.000000,0.000000,2.565000e+04,4.500000e+04,2052.000000,4.500000e+04,0.000533,-25184.000000,-17531.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,114570.500000,0.000000,0.000000,1.125000e+05,2.700000e+05,16456.500000,2.385000e+05,0.010006,-19644.000000,-2786.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,129076.000000,0.000000,0.000000,1.458000e+05,5.147775e+05,24939.000000,4.500000e+05,0.018850,-15731.000000,-1221.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,143438.500000,0.000000,1.000000,2.025000e+05,8.086500e+05,34596.000000,6.795000e+05,0.028663,-12378.500000,-292.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000
max,157875.000000,1.000000,11.000000,1.170000e+08,4.050000e+06,258025.500000,4.050000e+06,0.072508,-7680.000000,365243.000000,...,1.000000,1.000000,1.000000,1.00000,3.000000,6.000000,6.000000,24.000000,8.000000,25.000000

In [15]:
df_app.describe().columns

Index(['SK_ID_CURR', 'TARGET', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY', 'AMT_GOODS_PRICE',
       'REGION_POPULATION_RELATIVE', 'DAYS_BIRTH', 'DAYS_EMPLOYED',
       ...
       'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20',
       'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR',
       'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
       'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT',
       'AMT_REQ_CREDIT_BUREAU_YEAR'],
      dtype='object', length=106)

In [16]:
list(set(df_app.columns)-set(df_app.describe().columns))

['EMERGENCYSTATE_MODE',
 'CODE_GENDER',
 'FONDKAPREMONT_MODE',
 'WALLSMATERIAL_MODE',
 'FLAG_OWN_REALTY',
 'NAME_INCOME_TYPE',
 'NAME_HOUSING_TYPE',
 'NAME_EDUCATION_TYPE',
 'HOUSETYPE_MODE',
 'NAME_TYPE_SUITE',
 'ORGANIZATION_TYPE',
 'WEEKDAY_APPR_PROCESS_START',
 'NAME_CONTRACT_TYPE',
 'OCCUPATION_TYPE',
 'FLAG_OWN_CAR',
 'NAME_FAMILY_STATUS']

In [17]:
#dataframeobject.isnull()-
df_app.isnull()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,True,True
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49994,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
49995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
49996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
49997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
49998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [18]:
#pandas.isna(dataframeobject)- function that return null values.
pd.isna(df_app)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,True,True
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49994,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
49995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
49996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
49997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
49998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [19]:
df_app.isnull().sum()

SK_ID_CURR                       0
TARGET                           0
NAME_CONTRACT_TYPE               0
CODE_GENDER                      0
FLAG_OWN_CAR                     0
                              ...
AMT_REQ_CREDIT_BUREAU_DAY     6734
AMT_REQ_CREDIT_BUREAU_WEEK    6734
AMT_REQ_CREDIT_BUREAU_MON     6734
AMT_REQ_CREDIT_BUREAU_QRT     6734
AMT_REQ_CREDIT_BUREAU_YEAR    6734
Length: 122, dtype: int64

In [20]:
round(df_app.isnull().sum()/len(df_app)*100,2).sort_values(ascending=False)

COMMONAREA_MEDI             69.92
COMMONAREA_AVG              69.92
COMMONAREA_MODE             69.92
NONLIVINGAPARTMENTS_MODE    69.43
NONLIVINGAPARTMENTS_AVG     69.43
                            ...
NAME_FAMILY_STATUS           0.00
NAME_EDUCATION_TYPE          0.00
NAME_INCOME_TYPE             0.00
AMT_ANNUITY                  0.00
SK_ID_CURR                   0.00
Length: 122, dtype: float64

In [21]:
def missing_values(dataframe):
    return round(dataframe.isnull().sum()/len(df_app)*100,2).sort_values(ascending=False)

In [22]:
missing_values(df_app)

COMMONAREA_MEDI             69.92
COMMONAREA_AVG              69.92
COMMONAREA_MODE             69.92
NONLIVINGAPARTMENTS_MODE    69.43
NONLIVINGAPARTMENTS_AVG     69.43
                            ...
NAME_FAMILY_STATUS           0.00
NAME_EDUCATION_TYPE          0.00
NAME_INCOME_TYPE             0.00
AMT_ANNUITY                  0.00
SK_ID_CURR                   0.00
Length: 122, dtype: float64

In [25]:
df_prev=pd.read_csv(r"C:\Users\HP\pipeline python\python\python project\Bank loan case study\previous_application.csv")

In [ ]:
null=missing_values(df_app)[missing_values(df_app)>50]

In [ ]:
null.index

In [ ]:
df_app.drop(columns=null.index,inplace=True)

In [24]:
df_app["CODE_GENDER"]

0        M
1        F
2        M
3        F
4        M
        ..
49994    F
49995    M
49996    M
49997    F
49998    F
Name: CODE_GENDER, Length: 49999, dtype: object

In [27]:
df_app["CODE_GENDER"].value_counts()

CODE_GENDER
F      32823
M      17174
XNA        2
Name: count, dtype: int64

In [ ]:
df_app["CODE_GENDER"].value_counts()