In [1]:
pip install pandas

Requirement already satisfied: pandas in d:\anaconda\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in d:\anaconda\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\anaconda\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\anaconda\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in d:\anaconda\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in d:\anaconda\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [2]:
l=[10,20,30,40]
s=pd.Series(l)
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [3]:
l=[10,20,30,40]
s=pd.Series(l,index=["a","b","c","d"], name="python",dtype="float")
print(s)

a    10.0
b    20.0
c    30.0
d    40.0
Name: python, dtype: float64

In [6]:
d={"A":[10,20,30,40,50],"B":[100,200,300,400]}
s1=pd.Series(d)
print(s1)
print(type(s1))
print(s1["A"])

A    [10, 20, 30, 40, 50]
B    [100, 200, 300, 400]
dtype: object
<class 'pandas.core.series.Series'>
[10, 20, 30, 40, 50]

In [7]:
s=pd.Series(12,index=[1,2,3,4,5,6,7])
print(s)

1    12
2    12
3    12
4    12
5    12
6    12
7    12
dtype: int64

In [10]:
s1=pd.Series(12,index=[1,2,3,4,5,6,7])
s2=pd.Series(12,index=[1,2,3,4])
s3=s1+s2
print(s3)

1    24.0
2    24.0
3    24.0
4    24.0
5     NaN
6     NaN
7     NaN
dtype: float64

In [11]:
dic={"A":[10,20,30,40,50],"B":[100,200,300,400,500]}
df=pd.DataFrame(dic)
print(df)
print(type(df))
print(df["A"])

    A    B
0  10  100
1  20  200
2  30  300
3  40  400
4  50  500
<class 'pandas.core.frame.DataFrame'>
0    10
1    20
2    30
3    40
4    50
Name: A, dtype: int64

In [4]:
dic={"A":[10,20,30,40,50],"B":[100,200,300,400,500],
     1:[1000,2000,3000,4000,5000], "S":[1,2,3,4,5]}
df=pd.DataFrame(dic,columns=["A",1],index=["a","s","d","e","f"],dtype="float")
df

      A       1
a  10.0  1000.0
s  20.0  2000.0
d  30.0  3000.0
e  40.0  4000.0
f  50.0  5000.0

In [6]:
#arithmatic
df=pd.DataFrame({"A":[10,20,30,40,50],"B":[1,2,3,4,5]})
df

    A  B
0  10  1
1  20  2
2  30  3
3  40  4
4  50  5

In [8]:
df["C"]=df["A"]+df["B"]
df

    A  B   C
0  10  1  11
1  20  2  22
2  30  3  33
3  40  4  44
4  50  5  55

In [9]:
df["C"]=df["A"]-df["B"]
df

    A  B   C
0  10  1   9
1  20  2  18
2  30  3  27
3  40  4  36
4  50  5  45

In [10]:
df["C"]=df["A"]**df["B"]
df

    A  B          C
0  10  1         10
1  20  2        400
2  30  3      27000
3  40  4    2560000
4  50  5  312500000

In [11]:
df["C"]=df["A"]/df["B"]
df

    A  B     C
0  10  1  10.0
1  20  2  10.0
2  30  3  10.0
3  40  4  10.0
4  50  5  10.0

In [12]:
df["C"]=df["A"]//df["B"]
df

    A  B   C
0  10  1  10
1  20  2  10
2  30  3  10
3  40  4  10
4  50  5  10

In [16]:
df["Python"]=df["A"]<=30
df["Python_1"]=df["B"]<=3
df

    A  B   C  Python  Python_1  Pythonn
0  10  1  10    True      True     True
1  20  2  10    True      True     True
2  30  3  10    True      True     True
3  40  4  10   False     False    False
4  50  5  10   False     False    False

In [20]:
df.insert(1,"python_3",df["A"])

In [21]:
df

    A  python_3  B   C  Python  Python_1  Pythonn
0  10        10  1  10    True      True     True
1  20        20  2  10    True      True     True
2  30        30  3  10    True      True     True
3  40        40  4  10   False     False    False
4  50        50  5  10   False     False    False

In [ ]:
df1.insert(2,"python_2",[])